### ISSUE TITLE
Conflito com dependências (NodeJS)

### ISSUE THREAD

**Issue by S0raWasTaken** [Tuwave-Linux/repository#4]
_aproveito e deixo um template de issue pronto pra vcs usarem_

**Pacotes com problema:** `node-current` e `node-lts`

**Breve resumo do problema:** Ao instalar algum dos pacotes do NodeJS, outros programas que usam o pacote `nodejs` dos repositórios normais como dependência, tentam instalar o pacote `nodejs` por cima dos pacotes do repositório Tuwave, assim gerando um conflito.

**Logs:** Já faz tempo que resolvi instalando de outro repositório, mas o erro era basicamente sobre não poder sobreescrever o arquivo `/usr/bin/node`, que foi instalado com o `node-*` do Tuwave

O problema poderia ser resolvido mantendo apenas um dos pacotes do `nodejs` com o nome original.

**Comment by RedsonBr140** [comment]
O problema foi resolvido usando as tags `Provides` e `Conflicts` no control do pacote:
```
Package: node-lts
Version: 14.17.5-debian
Architecture: amd64
Maintainer: Tuwave Linux <tuwavelinux@yandex.com>
Installed-Size: 96256
Section: default
Priority: extra
homepage: http://nodejs.org
Conflicts: node-current, nodejs
Provides: nodejs, npm
Description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.
```
No caso, o control acima é do lts, porem, o do current está bem parecido com isso.
